# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GPUImage_AddFilterToCamera' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GPUImage_AddFilterToCamera
pod “GPUImage”
end
